### ISSUE TITLE
Huaxing panel

### ISSUE THREAD

**Issue by phodina** [map220v/sm8150-mainline#1]
Hi @map220v ,

thanks for the port. Would you have any suggestion how to run this on the Xiaomi Pad 5 with the AMOLED Huaxing panel?

If use the patches on top of 6.6 I get the kernel booting but as soon as it switches the DRM on the panel it goes dark.

I looked into the Xiaomi Kernel source code repo on github for the definition of the panel as there's a nice project that can convert that into a driver, that needs some polishing.

I tried the Windows 11 on the tablet and the boot image with the UEFI support was able to driver the panel correctly.

Should I extract the dtb, convert it into the dts with dtc, then run the script to get the driver with the sequences and timings for the display? Or is there another way how to bring the panel to life?

https://github.com/MiCode/Xiaomi_Kernel_OpenSource  -- nabu-r-oss

https://github.com/msm8916-mainline/linux-mdss-dsi-panel-driver-generator

https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/2-install-en.md

**Comment by map220v** [comment]
This fork already has support for Huaxing PPA957DB2 panel added here https://github.com/map220v/sm8150-mainline/commit/3ac6d2e5639cf9f2ae9f5bb9cec1aec31f8022e5
Make sure that you have kernel config created with "make defconfig sm8150.config"
