### ISSUE TITLE
Xiaomi nabu wifi drivers. And where pm8150b_fg pull battery data

### ISSUE THREAD

**Issue by catmengi** [map220v/sm8150-mainline#10]
Which wifi drivers does xiaomi nabu use? Which driver is handling pm8150b_fg. And does all charging drivers and pm8150b_fg(especially it) pull info from battery node in dts?

**Comment by map220v** [comment]
WCN3991(ath10k) driver is used for wifi, although schematic says that we have WCN3998, nabu seem to be the only sm8150 device that uses different qualcomm's wifi/bluetooth chip.

[qcom_fg](https://github.com/map220v/sm8150-mainline/blob/nabu-6.7/drivers/power/supply/qcom_fg.c) is used for reading pm8150b fuelgauge regs like MONOTONIC_SOC which contains battery percentage. Idk if all fuelgauges use battery node, here battery node is used to know battery capacity(used in linux to properly calculate time until battery charge is depleted) and min/max output voltage.
