### ISSUE TITLE
Ln8000 typec charging voltage and it controller

### ISSUE THREAD

**Issue by catmengi** [map220v/sm8150-mainline#11]
Which driver control charging voltage, tcpm.c (saw things about PD and PPS) or ln8000_charger.c or ln8000_charger.c configure ln8000 and it automatically control PD VBUS? Which voltage is standart 5v, 9v or even 12v?

**Comment by map220v** [comment]
tcpm.c should control PD protocol, ln8000 chip doesn't know anything about PD and it is only connected to usb vbus, PD protocol uses CC line of Type-C to do PD negotiation with charger. Voltage is also selected by tcpm.c, it should use best available PD profile that charger sent using PD protocol. PD capabilities and voltage limits specified in sink-pdos.

**Comment by catmengi** [comment]
> tcpm.c should control PD protocol, ln8000 chip doesn't know anything about PD and it is only connected to usb vbus, PD protocol uses CC line of Type-C to do PD negotiation with charger. Voltage is also selected by tcpm.c, it should use best available PD profile that charger sent using PD protocol. PD capabilities and voltage limits specified in sink-pdos.

Where sink-pdos is specified?

**Comment by catmengi** [comment]
Sorry for wasting your time by this ⬆️ question

> > tcpm.c should control PD protocol, ln8000 chip doesn't know anything about PD and it is only connected to usb vbus, PD protocol uses CC line of Type-C to do PD negotiation with charger. Voltage is also selected by tcpm.c, it should use best available PD profile that charger sent using PD protocol. PD capabilities and voltage limits specified in sink-pdos.
> 
> Where sink-pdos is specified?

S i already found, should it be 5v-15v 3a?

**Comment by catmengi** [comment]
I already found sink-pdos, should it be 5v-12v 3a?

**Comment by map220v** [comment]
> I already found sink-pdos, should it be 5v-12v 3a?

[Yes](https://github.com/map220v/sm8150-mainline/blob/9894da172d3f6433475489d2d3332dd7b437c105/arch/arm64/boot/dts/qcom/sm8150-xiaomi-nabu.dts#L719), it is 5v-12v and 3a or less.
