### ISSUE TITLE
Which kernel version is working?

### ISSUE THREAD

**Issue by panpanpanpaan** [map220v/sm8150-mainline#13]
i want to test this with my xiaomi nabu, but as far i know, 6.7 and 6.8 are broken, so, should i use 6.6?

**Comment by map220v** [comment]
Use 6.7 with these commits reverted: https://github.com/map220v/sm8150-mainline/commit/960b9b92de1dce081fce4d562efe9ce4c7459d66 https://github.com/map220v/sm8150-mainline/commit/36862377382413681fb3c9776860f3f5b0509fd9 https://github.com/map220v/sm8150-mainline/commit/f2bbf3da60c9e74d9fe888bec7aad055b2c74e9b
it should work better than 6.6

**Comment by panpanpanpaan** [comment]
thank you! if i use this commit should i be okay? [9894da172d3f6433475489d2d3332dd7b437c105](https://github.com/map220v/sm8150-mainline/commit/9894da172d3f6433475489d2d3332dd7b437c105) is there a list in what is working and what is not?

**Comment by panpanpanpaan** [comment]
Sorry if i bother you, but could you review if this should be okay? it's an pmos aports config, i can't test it cause im still waiting to my tablet to be unlocked (you don't need to compile if you want, just tell me if the firmware config it's okay :DD) https://we.tl/t-1UgrjcLbBB

**Comment by map220v** [comment]
It won't work with branch nabu-6.4 or newer because firmware paths in firmware-xiaomi-nabu are outdated, also pmos edge will give errors because APKBUILD in linux-postmarketos-qcom-sm8150-nabu is outdated.
Use [test branch](https://github.com/map220v/postmarket_xiaomi_nabu/tree/test) it has these problems fixed, and don't forget to regenerate config-postmarketos-qcom-sm8150-nabu.aarch64 using 6.7 defconfig and sm8150.config

**Comment by panpanpanpaan** [comment]
i got it working!, it works great, but the screen can't come back when turn it off and on, is this a known problem?

**Comment by map220v** [comment]
> i got it working!, it works great, but the screen can't come back when turn it off and on, is this a known problem?

Yes, dsi suspend/resume is broken on sm8150 since 6.2

**Comment by panpanpanpaan** [comment]
oh, that's a shame, i guess there is no workaround or patch to solve it

**Comment by panpanpanpaan** [comment]
btw, is there a reason on not upstreaming your pmos port in apkports? would you be bother if i do that?

**Comment by map220v** [comment]
> btw, is there a reason on not upstreaming your pmos port in apkports? would you be bother if i do that?

I stopped working on it and mainline linux port, because Windows port was my main priority. Also I can't test anything now to fix current mainline linux issues, because my Pad 5 is bricked and can only enter EDL. You can upstream pmos and kernel patches if you want.

**Comment by panpanpanpaan** [comment]
oh, it's sad to hear that, thank you for your great job!
