### ISSUE TITLE
The error about gpu...

### ISSUE THREAD

**Issue by chkkv** [map220v/sm8150-mainline#14]
I built debian rootfs and this kernel (ver. 6.8.0).
System boot successful but screen is black.
Firmware is cloned from [https://github.com/map220v/ubuntu-xiaomi-nabu](url)

This is log from kernel:
[dmesg.log](https://github.com/map220v/sm8150-mainline/files/15286746/dmesg.log)

I noticed this:
`[    0.456392] adreno 2c00000.gpu: [drm:adreno_zap_shader_load] *ERROR* Unable to load qcom/sm8150/xiaomi/nabu/a640_zap.mbn`
`[    0.456482] msm_dpu ae01000.display-controller: [drm:adreno_load_gpu] *ERROR* gpu hw init failed: -2
`
I can confirm "a640_zap.mbn" has been placed at “/lib/firmware/qcom/sm8150/xiaomi/nabu/a640_zap.mbn”.But why is this?

**Comment by map220v** [comment]
Clone nabu-v6.7 branch and ```git checkout 9894da172d3f6433475489d2d3332dd7b437c105``` only this version has both display and ufs working.

a640_zap.mbn error happend because linux kernel checked for it before rootfs mounted, you can ignore it since it should try to load it again later.
