### ISSUE TITLE
Is it possible to make kernel use FB instead of dsi?

### ISSUE THREAD

**Issue by catmengi** [map220v/sm8150-mainline#18]
Is it possible to make kernel use bootup framebuffer instead of dsi? Will this close black screen issue? Also any news on ufs?

**Comment by map220v** [comment]
It's possible to use simplefb, but vsync, rotation and gpu won't be available, mesa lib requires compatible drm device for gpu rendering(simpledrm is not one of them).
Idk if ufs clocks are still broken or not with dual dsi being used on sm8150, they do work fine on sm8250 and sm8550.

**Comment by catmengi** [comment]
> It's possible to use simplefb, but vsync, rotation and gpu won't be available, mesa lib requires compatible drm device for gpu rendering(simpledrm is not one of them). Idk if ufs clocks are still broken or not with dual dsi being used on sm8150, they do work fine on sm8250 and sm8550.

If ufs isnt working i dont think this project still need for me(, it is very non comfort to use such thing as usb flash drive as root + newer kernels still dont fix ufs(
