### ISSUE TITLE
Question about xiaomi keyboard compatibility.

### ISSUE THREAD

**Issue by Xunflash** [map220v/sm8150-mainline#22]
I am a user of Xiaomi Pad 5 pro. I am helping the SM8250 mainline kernel developer test Xiaomi Pad 5 pro, but I found that the keyboard of Xiaomi Pad 5 pro will break links from time to time. Since Xiaomi Pad 5 pro and Xiaomi Pad 5 use the same keyboard, I accessed your kernel code, and I noticed that the code of the mainline kernel is somewhat different, which seems to be different on gpio. 

How did you find the corresponding gpio and write the dtsi file? (Sorry I'm not a kernel developer, and some descriptions may be inaccurate, but I want to support the improvement of the elish device mainline kernel as much as I can.)

Here are the commit related to elish:
https://gitlab.com/sm8250-mainline/linux/-/commit/b833aa079f557c716afb1d421153b070466a2fa5

**Comment by map220v** [comment]
I got these gpio's from [nabu-pinctrl](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/71b6effd2dfa8f703dd1ea17acd1323b2fd3cf6c/arch/arm64/boot/dts/qcom/nabu-pinctrl.dtsi#L608) and [xiaomi_keyboard](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/71b6effd2dfa8f703dd1ea17acd1323b2fd3cf6c/arch/arm64/boot/dts/qcom/nabu-sm8150.dtsi#L564) node, drive-strength for these pins are from /sys/kernel/debug/gpio

**Comment by map220v** [comment]
I just checked info about gpio155 on sm8250, and it seem to be used by lpass(adsp) as lpass_gpio9, so you would need to add gpio9 to [lpass_tlmm](https://github.com/torvalds/linux/blob/a430d95c5efa2b545d26a094eb5f624e36732af0/arch/arm64/boot/dts/qcom/sm8250.dtsi#L2805) and remove gpio155 from tlmm node

**Comment by Xunflash** [comment]
> and it seem to be used by lpass(adsp) as lpass_gpio9

Could you please tell me where is the code to find gpio155 used as lpass_gpio9?

**Comment by map220v** [comment]
> > and it seem to be used by lpass(adsp) as lpass_gpio9
> 
> Could you please tell me where is the code to find gpio155 used as lpass_gpio9?

Idk if there is any info in code about that, I got info about gpio155 from sm8250 datasheet, it says that gpio155 is gpio9 on lpass, and for example on my sm7125 device all lpass_gpio's aren't available in tlmm, so the only way to configure pin for them is using lpass_tlmm.
![gpio155](https://github.com/user-attachments/assets/3e3f1c93-4f87-4bf9-b343-d75da168a6e4)

**Comment by Xunflash** [comment]
Thank you very much for your answer. Now keyboard can work normally on elish.
