### ISSUE TITLE
Possibility of using libhybris for gpu

### ISSUE THREAD

**Issue by catmengi** [map220v/sm8150-mainline#23]
Is it possible to fix gpu subsystem using libhybris and mainline linux kernel? Also does anybody know is ufs working in new kernel version or it still broken? Also possible is it to track down issue of a black display via debugger?

**Comment by map220v** [comment]
Adreno 640 already works fine with mesa. UFS seem to work fine in 6.11 and black screen on boot is fixed here http://gitlab.postmarketos.org/panpanpanpan/sm8150-mainline/-/commits/6.11-wip

**Comment by catmengi** [comment]
Thanks! I should give it a try a build rootfs of ubuntu for it)
