### ISSUE TITLE
Does ln8000 automatically set charging voltage?

### ISSUE THREAD

**Issue by catmengi** [map220v/sm8150-mainline#7]
Does ln8000 know how to charge battery, set coltage and amperage (or it is controlled by driver) and low voltage and/or wattage when battery is full(Is this implemented)? And does PD PPS supported?(Or it doesnt need?)

**Comment by map220v** [comment]
ln8000 chip knows how to charge battery properly, ln8000 driver only sets settings and enables charging mode when it's possible, ln8000 chip monitors battery voltage so when battery voltage increases charge speed gets lower, in my test at 100% it's almost doesn't charge battery.
If Type-C driver supports PD PPS protocol then it should work.
